# Generated by Django 3.1.4 on 2021-01-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0018_auto_20210109_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistAnimator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date used')),
                ('animators', models.ManyToManyField(to='members.Member')),
            ],
        ),
    ]
