# Generated by Django 3.1.4 on 2021-01-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0018_auto_20210109_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_invoice', models.DateTimeField(verbose_name='Invoice date')),
                ('status', models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('cancelled', 'cancelled')], max_length=10)),
                ('date_paid', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Paid date')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'cash'), ('twint', 'twint'), ('bank', 'bank')], default=None, max_length=10, null=True)),
                ('comments', models.TextField(blank=True, default=None, max_length=2000, null=True)),
                ('member', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date used')),
                ('qty', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('invoice', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.invoice')),
                ('member', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.member')),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.project')),
                ('resource', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.resource')),
            ],
        ),
    ]
