# Generated by Django 3.1.4 on 2021-01-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='price',
            new_name='price_member',
        ),
        migrations.AddField(
            model_name='resource',
            name='payable_by_animation_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='price_not_member',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5),
            preserve_default=False,
        ),
    ]
