# Generated by Django 3.1.4 on 2021-01-09 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20210109_1212'),
        ('invoicing', '0002_auto_20210109_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount_machine', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount_cash', models.DecimalField(decimal_places=2, max_digits=6)),
                ('invoice', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.invoice')),
                ('member', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.member')),
            ],
        ),
    ]
