# Generated by Django 3.1.4 on 2021-01-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20210109_1212'),
        ('invoicing', '0003_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='AccountEntry',
        ),
    ]
