# Generated by Django 3.1.4 on 2021-01-09 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20210109_1212'),
        ('invoicing', '0005_auto_20210109_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountentry',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='accountentry',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='members.member'),
            preserve_default=False,
        ),
    ]
