# Generated by Django 3.1.4 on 2021-01-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_auto_20210109_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentry',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
