# Generated by Django 3.1.4 on 2021-01-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_auto_20210109_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usage',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
