# Generated by Django 3.1.4 on 2021-01-09 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20210109_1212'),
        ('invoicing', '0008_auto_20210109_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='edited_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='editor', to='members.member'),
        ),
    ]
