# Generated by Django 3.1.5 on 2021-01-09 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_usage_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_invoice',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Invoice date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('cancelled', 'cancelled')], default='created', max_length=10),
        ),
    ]
