# Generated by Django 3.1.5 on 2021-01-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_auto_20210109_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
