# Generated by Django 3.1.5 on 2021-01-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0016_resource_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage',
            old_name='invoice_number',
            new_name='invoice',
        ),
    ]
