# Generated by Django 3.1.5 on 2021-01-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0017_auto_20210111_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.CharField(default='nope', max_length=200),
            preserve_default=False,
        ),
    ]
