# Generated by Django 3.1.5 on 2021-01-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0020_auto_20210112_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
