# Generated by Django 3.1.5 on 2021-01-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0022_resource_logger_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
