# Generated by Django 3.1.5 on 2021-01-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0024_auto_20210112_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='usage',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
