# Generated by Django 3.1.5 on 2021-01-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('invoicing', '0026_resourcecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Unit',
            new_name='ResourceUnit',
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.resourcecategory'),
        ),
        migrations.AddField(
            model_name='resource',
            name='widget',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.resourcewidget'),
        ),
    ]
