# Generated by Django 3.1.5 on 2021-01-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0029_auto_20210116_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='qty',
            field=models.FloatField(),
        ),
    ]
