# Generated by Django 3.1.5 on 2021-01-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0032_expense_expensetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='processed',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='expense',
            name='topaye',
            field=models.BooleanField(default=None),
        ),
    ]
