# Generated by Django 3.1.5 on 2021-02-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0033_auto_20210118_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
