# Generated by Django 3.1.5 on 2021-03-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0034_auto_20210206_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount_due',
        ),
    ]
