# Generated by Django 3.1.5 on 2021-04-02 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0035_remove_invoice_amount_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('rappel1', '1er rappel'), ('rapell2', ' 2ème rappel'), ('cancelled', 'cancelled')], default='created', max_length=10),
        ),
    ]
