# Generated by Django 3.1.5 on 2021-04-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0036_auto_20210402_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount_deduction',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_deduction_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_deduction_machine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
