# Generated by Django 3.2 on 2021-05-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0037_auto_20210402_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('paid', 'Payé'), ('rappel1', '1er rappel'), ('rapell2', ' 2ème rappel'), ('cancelled', 'cancelled')], default='created', max_length=10),
        ),
    ]
