# Generated by Django 3.2 on 2021-05-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0038_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountentry',
            options={'verbose_name_plural': 'Account entries'},
        ),
        migrations.AlterModelOptions(
            name='resourcecategory',
            options={'verbose_name_plural': 'Resource categories'},
        ),
    ]
