# Generated by Django 3.2 on 2021-05-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0041_auto_20210520_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(unique=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'cash'), ('twint', 'twint'), ('bank', 'bank')], default=None, max_length=10, null=True)),
                ('comments', models.TextField(blank=True, default=None, max_length=2000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(unique=True),
        ),
    ]
