# Generated by Django 3.2 on 2021-05-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0042_auto_20210524_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='invoice_paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='date_paid',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Paid date'),
        ),
    ]
