# Generated by Django 3.2 on 2022-02-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0043_alter_invoice_date_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Usage Summary',
                'verbose_name_plural': 'Usages Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoicing.usage',),
        ),
        migrations.RemoveField(
            model_name='usage',
            name='valid',
        ),
    ]
