# Generated by Django 3.2 on 2022-12-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0045_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='price_consumable_only',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
