# Generated by Django 3.2 on 2022-12-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0048_resource_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.resourcecategory'),
        ),
    ]
