# Generated by Django 3.2 on 2023-01-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0049_resourcecategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
