# Generated by Django 3.2 on 2023-01-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0055_resource_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='layout',
            field=models.CharField(blank=True, choices=[('center', 'center'), ('full', 'full')], default=None, max_length=20, null=True),
        ),
    ]
