# Generated by Django 3.2.19 on 2023-10-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0057_auto_20231023_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='was_sent_by_post',
            field=models.BooleanField(default=False),
        ),
    ]
