# Generated by Django 3.2.19 on 2023-10-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0058_auto_20231028_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='year',
            field=models.IntegerField(blank=True, help_text='Only for year specific resources like membership', null=True),
        ),
    ]
