# Generated by Django 6.0.3 on 2026-06-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0059_alter_usage_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'To Invoice',
                'verbose_name_plural': 'To Invoice',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoicing.invoice',),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('twint', 'Twint'), ('bank', 'Banque'), ('frais', 'Note de frais'), ('perte', 'Non récupérable'), ('interne', 'Payée par le FabLab'), ('bon_fablab', 'Bon FabLab Sion'), ('cheque_sion', 'Chèque sport ou culture Ville de Sion')], default=None, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('paid', 'Payé'), ('rappel1', '1er rappel'), ('rappel2', ' 2ème rappel'), ('rappel3', ' 3ème rappel'), ('cancelled', 'cancelled')], default='created', max_length=10),
        ),
    ]
