# Generated by Django 3.1.4 on 2020-12-27 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_usage_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.member'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='resource',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.resource'),
        ),
    ]
