# Generated by Django 3.1.4 on 2020-12-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20201227_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='unit',
            field=models.CharField(default='undef', max_length=200),
            preserve_default=False,
        ),
    ]
