# Generated by Django 3.1.4 on 2020-12-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_resource_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='rfid',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
