# Generated by Django 3.1.4 on 2021-01-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.project'),
        ),
    ]
