# Generated by Django 3.1.4 on 2021-01-09 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_usage_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_invoice', models.DateTimeField(verbose_name='Invoice date')),
                ('date_paid', models.DateTimeField(verbose_name='Paid date')),
                ('status', models.CharField(choices=[('created', 'created'), ('paid', 'paid')], max_length=10)),
                ('member', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.member')),
            ],
        ),
        migrations.AddField(
            model_name='usage',
            name='invoice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.invoice'),
        ),
    ]
