# Generated by Django 3.1.4 on 2021-01-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='comments',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('cancelled', 'cancelled')], max_length=10),
        ),
    ]
