# Generated by Django 3.1.4 on 2021-01-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20210109_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('twint', 'twint'), ('bank', 'bank')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='comments',
            field=models.TextField(max_length=2000),
        ),
    ]
