# Generated by Django 3.1.4 on 2021-01-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20210109_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='comments',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_paid',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Paid date'),
        ),
    ]
