# Generated by Django 3.1.4 on 2021-01-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_checklistanimator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChecklistAnimator',
        ),
    ]
