# Generated by Django 3.1.4 on 2021-01-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_delete_checklistanimator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='member',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='resource',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='Usage',
        ),
    ]
