# Generated by Django 3.1.4 on 2021-01-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20210109_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rfid',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='visa',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
