# Generated by Django 3.1.5 on 2021-01-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('no member', 'no member'), ('member', 'memeber'), ('staff', 'staff'), ('committee', 'committee')], default='no member', max_length=10),
        ),
    ]
