# Generated by Django 3.1.5 on 2021-01-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mail',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
