# Generated by Django 3.1.5 on 2021-01-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_member_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='civility',
            field=models.CharField(choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Association', 'Association'), ('Entreprise', 'Entreprise')], default='no member', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='locality',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='npa',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
