# Generated by Django 3.1.5 on 2021-01-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_member_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
