# Generated by Django 3.1.5 on 2021-01-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_member_is_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bank_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='iban',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
