# Generated by Django 3.1.5 on 2021-02-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20210118_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='inscription_state',
            field=models.CharField(choices=[('not member', 'not member'), ('subscribed', 'subscribed'), ('member', 'member')], default='not member', max_length=20),
        ),
    ]
