# Generated by Django 3.1.5 on 2021-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_auto_20210212_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='member',
            name='civility',
            field=models.CharField(choices=[('Mme', 'Madame'), ('M', 'Monsieur'), ('Non souhaitée', 'Non souhaitée'), ('Association', 'Association'), ('Entreprise', 'Entreprise')], default='no member', max_length=20, verbose_name='Civilité'),
        ),
        migrations.AlterField(
            model_name='member',
            name='locality',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Localité'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mail',
            field=models.EmailField(blank=True, default=None, max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='member',
            name='npa',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='NPA'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Prénom'),
        ),
    ]
