# Generated by Django 3.1.5 on 2021-02-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_auto_20210212_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Téléphone'),
        ),
    ]
