# Generated by Django 3.1.5 on 2021-02-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_auto_20210216_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='civility',
        ),
    ]
