# Generated by Django 3.1.5 on 2021-02-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_remove_member_civility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
        migrations.AddField(
            model_name='member',
            name='is_committee',
            field=models.BooleanField(default=False, verbose_name='Comité'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='Membre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Animateur'),
        ),
    ]
