# Generated by Django 3.2 on 2021-05-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0037_member_is_resigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_type',
            field=models.CharField(blank=True, choices=[('membre', 'membre'), ('etudiant', 'étudiant'), ('passif', 'passif'), ('angel', 'angel'), ('alias', 'alias de facturation')], default=None, max_length=20, null=True),
        ),
    ]
