# Generated by Django 3.2 on 2022-03-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_member_member_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_added',
            field=models.DateField(default=None, null=True, verbose_name='Date ajout'),
        ),
        migrations.AddField(
            model_name='member',
            name='date_resigned',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date démission'),
        ),
    ]
