# Generated by Django 3.2 on 2022-03-19 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0041_alter_member_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='inscription_state',
        ),
        migrations.AlterField(
            model_name='member',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date ajout'),
        ),
    ]
