# Generated by Django 3.2 on 2022-06-20 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0042_auto_20220319_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.project')),
            ],
        ),
    ]
