# Generated by Django 3.2 on 2022-12-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0043_projectcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subscription_status',
            field=models.CharField(choices=[('subscribing ', '0 - Forumulaire remplis'), ('invoiced', '1 - Facture envoyée'), ('active', '2 - Active'), ('overdue', '3 - Débiteur'), ('resigned', '4 - Démission')], default='active', max_length=20, verbose_name="Etat de l'inscription"),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(blank=True, choices=[('membre', 'membre'), ('etudiant', 'étudiant'), ('passif', 'passif'), ('angel', 'angel'), ('alias', 'alias de facturation'), ('no_member', 'non-membre'), ('hes', 'cours hes')], default=None, max_length=20, null=True),
        ),
    ]
