# Generated by Django 3.2 on 2022-12-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_auto_20221222_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_member',
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('membre', 'Membre'), ('etudiant', 'Etudiant'), ('passif', 'Passif'), ('angel', 'Angel'), ('alias', 'Alias de facturation'), ('no_member', 'Non-membre'), ('hes', 'HES cours ou labo'), ('interne', 'Interne')], default='membre', max_length=20),
        ),
    ]
