# Generated by Django 3.2.19 on 2023-10-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0047_alter_member_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='preferred_invoice_method',
            field=models.CharField(choices=[('email', 'email'), ('post', 'post')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('membre', 'Membre'), ('etudiant', 'Etudiant'), ('passif', 'Passif'), ('angel', 'Angel'), ('alias', 'Alias de facturation'), ('no_member', 'Non-membre'), ('hes', 'HES cours ou labo'), ('ell', 'Energy Living Lab'), ('interne', 'Interne')], default='membre', max_length=20),
        ),
    ]
