# Generated by Django 3.2.19 on 2023-10-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0048_auto_20231023_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_allowed_to_open_cash_register',
            field=models.BooleanField(default=False, verbose_name='Ouverture caisse (pour non animateur)'),
        ),
    ]
