# Generated by Django 3.2.19 on 2024-07-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0049_member_is_allowed_to_open_cash_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_resigned',
        ),
    ]
