# Generated by Django 3.2.19 on 2024-09-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0050_remove_member_is_resigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('membre', 'Membre'), ('etudiant', 'Etudiant'), ('avs', 'AVS'), ('ai', 'AI'), ('passif', 'Passif'), ('angel', 'Angel'), ('alias', 'Alias de facturation'), ('no_member', 'Non-membre'), ('hes', 'HES cours ou labo'), ('ell', 'Energy Living Lab'), ('interne', 'Interne')], default='membre', max_length=20),
        ),
    ]
