# Generated by Django 4.2.16 on 2024-12-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0052_member_swiss_engineering_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='comment',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='Commentaire'),
        ),
    ]
