# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ develop, main]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
      continue-on-error: true
    - name: Test
      run: |
        pip install pytest
        python manage.py test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build docker image for web
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.prod
          tags:  ghcr.io/alexsierro/fabman/web:latest
          outputs: type=oci,dest=~/mytmp/myimage.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: ~/mytmp/myimage.tar


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: ~/mytmp
      - name: Load image
        run: |
          docker load --input ~/mytmp/myimage.tar
          docker image ls -a
      - name: Push image
        run: |
          docker image push ghcr.io/alexsierro/fabman/web:latest
